volumes:
  prometheus_data: {}
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: bugna_grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ./docker/grafana:/var/lib/grafana
    env_file:
      - ./docker/grafana.env
    ports:
      - 3001:3001
    extra_hosts:
      - host.docker.internal:host-gateway
  prometheus:
    image: prom/prometheus:latest
    container_name: bugna_prom
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9091
    extra_hosts:
      - host.docker.internal:host-gateway
