volumes:
  prometheus_data: {}
services:
  bugna_bridge:
    image: bugna_bridge:latest
    container_name: bugna_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-log=true'
      - '-stats=false'
      - '-stratum=:5556'
      - '-prom=:2115'
      - '-bugna=host.docker.internal:38138'
      - '-mindiff=64'
      - '-vardiff=true'
    ports:
      - 5556:5556
      - 2115:2115
    extra_hosts:
      - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana-oss:latest
    container_name: bugna_grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ./docker/grafana:/var/lib/grafana
#    env_file:
#      - ./docker/grafana.env
    ports:
      - 3001:3001
    extra_hosts:
      - host.docker.internal:host-gateway
  prometheus:
    image: prom/prometheus:latest
    container_name: bugna_prom
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus-internal.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9091
    extra_hosts:
      - host.docker.internal:host-gateway
